name: Create draft release
description: Create a draft GitHub Release using VERSION from Dockerfile (YYYY.MM.DD). Fails if VERSION is missing or malformed.

inputs:
  tag_prefix:
    description: Optional prefix for the tag (e.g. v). Default is empty.
    required: false
    default: ""
  dockerfile_path:
    description: Path to Dockerfile to parse version from
    required: false
    default: Dockerfile
  target:
    description: Git ref/sha to tag (default: current commit SHA)
    required: false
    default: ""
  generate_notes:
    description: Whether to auto-generate release notes (true/false)
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Extract and validate VERSION
      id: ver
      shell: bash
      run: |
        set -euo pipefail
        df="${{ inputs.dockerfile_path }}"

        if [ ! -f "$df" ]; then
          echo "::error::Dockerfile not found at: $df"
          exit 1
        fi

        if grep -q "LABEL org.opencontainers.image.version=" "$df"; then
          version=$(grep "LABEL org.opencontainers.image.version=" "$df" | head -1 | cut -d '=' -f2- | tr -d ' "')
        elif grep -q "LABEL VERSION=" "$df"; then
          version=$(grep "LABEL VERSION=" "$df" | head -1 | cut -d '=' -f2- | tr -d ' "')
        else
          echo "::error::No VERSION label found in $df"
          exit 1
        fi

        if ! echo "$version" | grep -Eq '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'; then
          echo "::error::Invalid VERSION format: '$version' (expected YYYY.MM.DD)"
          exit 1
        fi

        tag="${{ inputs.tag_prefix }}${version}"
        echo "Resolved tag: $tag"
        echo "TAG=$tag" >> "$GITHUB_ENV"

    - name: Create draft release (fails if tag already exists)
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        tag="${TAG}"
        title="Release ${tag}"
        target="${{ inputs.target }}"

        if [ -z "$target" ]; then
          target="${GITHUB_SHA}"
        fi

        if gh release view "$tag" >/dev/null 2>&1; then
          echo "::error::Release for tag '$tag' already exists."
          exit 1
        fi

        args=(release create "$tag" --draft --title "$title" --target "$target")

        if [ "${{ inputs.generate_notes }}" = "true" ]; then
          args+=(--generate-notes)
        fi

        gh "${args[@]}"
        echo "✓ Draft release created for tag $tag"
